<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<PlatformTarget>x64</PlatformTarget>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentAssertions" Version="8.8.0" />
		<PackageReference Include="Microsoft.TestPlatform.TestHost" Version="18.0.1" />
		<PackageReference Include="Moq" Version="4.20.72" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.0" />
		<PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.0" />
		<PackageReference Include="xunit" Version="2.9.3" />
		<PackageReference Include="xunit.analyzers" Version="1.26.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="xunit.assert" Version="2.9.3" />
		<PackageReference Include="xunit.extensibility.execution" Version="2.9.3" />
		<PackageReference Include="xunit.runner.utility" Version="2.9.3" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<!-- Автоматичне копіювання Kingsrow64.dll у bin\Debug\net9.0\ -->
	<ItemGroup>
		<None Update="Kingsrow64.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="egdb64.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Kingsrow.odb">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="weights_v4.bin">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="weights_nk_v4.bin">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>